#cp -p /home/rd/xtwse/LibXS/Makefile.am /home/dev/xtwse/LibXS
#cp -pd /home/rd/xtwse/kwaylib/lib/libsneSignonAdm2.la       /home/dev/xtwse/kwaylib/lib
#cp -pd /home/rd/xtwse/kwaylib/lib/libsneTwStk.la            /home/dev/xtwse/kwaylib/lib
#cp -pd /home/rd/xtwse/kwaylib/lib/libxs.la                  /home/dev/xtwse/kwaylib/lib
#cp -pd /home/rd/xtwse/kwaylib/lib/libxsSignon.la            /home/dev/xtwse/kwaylib/lib
#cp -pd /home/rd/xtwse/kwaylib/lib/libxsSignonSvrDB.la       /home/dev/xtwse/kwaylib/lib
#cp -pd /home/rd/xtwse/kwaylib/lib/libxsTwStk.la             /home/dev/xtwse/kwaylib/lib
#cp -pd /home/rd/xtwse/kwaylib/lib/libxsfmerg.la             /home/dev/xtwse/kwaylib/lib
cp -p /home/rd/xtwse/LibXS/*.h /home/dev/xtwse/LibXS
cp -pd /home/rd/xtwse/kwaylib/lib/libsneSignonAdm2.so       /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libsneSignonAdm2.so.0     /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libsneSignonAdm2.so.0.0.0 /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libsneTwStk.so            /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libsneTwStk.so.0          /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libsneTwStk.so.0.0.0      /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libxs.so                  /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libxs.so.0                /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libxs.so.0.0.0            /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libxsSignon.so            /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libxsSignon.so.0          /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libxsSignon.so.0.0.0      /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libxsSignonSvrDB.so       /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libxsSignonSvrDB.so.0     /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libxsSignonSvrDB.so.0.0.0 /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libxsTwStk.so             /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libxsTwStk.so.0           /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libxsTwStk.so.0.0.0       /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libxsfmerg.so             /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libxsfmerg.so.0           /home/dev/xtwse/kwaylib/lib
cp -pd /home/rd/xtwse/kwaylib/lib/libxsfmerg.so.0.0.0       /home/dev/xtwse/kwaylib/lib